application: python3wos2
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /static
  static_dir: static

- url: /tasks/.*
  script: wsgi.py
  login: admin

- url: /.*
  script: wsgi.py
  secure: optional

skip_files:
- .*\.deprecated
- .*\.cache.*
- .*\.log
- .*\.svn
- .*\.cmd
